# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # https://docs.vagrantup.com.
  # config.vm.box = "generic/arch"
  config.vm.box = "ubuntu/bionic64"

  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"
  # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  config.vm.synced_folder "./", "/home/vagrant/workspace"

  config.vm.provision "shell", inline: <<-SHELL
    # sudo pacman Syu --noconfirm
    # suod pacman -S git vim devtools base-devel --needed --noconfirm
    sudo DEBIAN_FRONTEND=noninteractive apt-get -y install git

    curl -O https://storage.googleapis.com/golang/go1.13.15.linux-amd64.tar.gz

    #unzip the archive
    tar -xvf go1.13.15.linux-amd64.tar.gz

    #move the go lib to local folder
    mv go /usr/local

    #delete the source file
    rm go1.13.15.linux-amd64.tar.gz

    #only full path will work
    touch /home/vagrant/.bash_profile

    echo "export PATH=$PATH:/usr/local/go/bin" >> /home/vagrant/.bash_profile

    echo "export GOPATH=/home/vagrant/go:$PATH" >> /home/vagrant/.bash_profile

    export GOPATH=/home/vagrant/go

    mkdir -p "$GOPATH/bin"
  SHELL

   config.vm.provision :shell, :path => "bootstrap.sh"

end
