# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # https://docs.vagrantup.com.
  config.vm.box = "generic/arch"

    # set the hostname
    config.vm.hostname = "gosystem.dev"

    #set the shared folder
    # config.vm.synced_folder "src", "/home/vagrant/workspace/src"
    config.vm.synced_folder "./", "/home/vagrant/workspace"

    #provision the box
    config.vm.provision :shell, :path => "setup/bootstrap.sh"

    #port forwarding
    config.vm.network "forwarded_port", guest: 5000, host: 5000,
        auto_correct: true
    # SHELL

end
